# Product copy. HR from the current helios-gea.com product pages; EN is our translation (to be checked by Neva).
BASE_LOTION_HR = "Potpuno prirodna krema-losion od 45 Degrees za duboku i intenzivnu njegu kože tijela. Sadrži organsku kominu masline premium kvalitete iz istarskih eko maslinika bogatu antioksidansima i mineralima."
BASE_LOTION_EN = "A completely natural cream lotion by 45 Degrees for deep, intensive body care. It contains premium organic olive pulp from Istrian eco olive groves, rich in antioxidants and minerals."
POLISH_HR = "Potpuno prirodni piling za tijelo od 45 Degrees sadrži organsku kominu masline premium kvalitete iz istarskih eko maslinika, bogati izvor antioksidansa i minerala. Ulje sjemenki grožđa, ulje masline i shea maslac oplemenjeni esencijama naranče, petit graina, vanilije i paprene metvice energiziraju i nadahnjuju osjetila. Ekstrakt preslice i mljevene koštice masline stvaraju nježni piling efekt koji pouzdano odstranjuje mrtve stanice epiderme i pružaju koži osjećaj zategnutosti. Koža je dubinski nahranjena, svilenkasta na dodir i svježeg izgleda."
POLISH_EN = "A completely natural body scrub by 45 Degrees containing premium organic olive pulp from Istrian eco olive groves, a rich source of antioxidants and minerals. Grape seed oil, olive oil and shea butter, enriched with essences of orange, petitgrain, vanilla and peppermint, energise and inspire the senses. Horsetail extract and ground olive stones create a gentle exfoliating effect that reliably removes dead skin cells and leaves the skin feeling firm. The skin is deeply nourished, silky to the touch and fresh-looking."
FOOT_HR = "Potpuno prirodni Absolute Foot Balm od 45 Degrees sadrži organsku kominu masline premium kvalitete iz istarskih eko maslinika, bogati izvor antioksidansa i minerala. Laneno ulje dubinski hrani i obnavlja kožu, a esencije paprene metvice i muškatne kadulje osvježavaju i opuštaju. Ekstrakt preslice, gaveza i ružmarina doprinose osjećaju ugode i lakoće. Stopala su dubinski nahranjena, obnovljena i osvježena."
FOOT_EN = "The completely natural Absolute Foot Balm by 45 Degrees contains premium organic olive pulp from Istrian eco olive groves, a rich source of antioxidants and minerals. Linseed oil deeply nourishes and renews the skin, while essences of peppermint and clary sage refresh and relax. Horsetail, comfrey and rosemary extracts add a feeling of comfort and lightness. Feet are deeply nourished, renewed and refreshed."
WOMEN_HR = "Potpuno prirodna njega ruku formulirana za žene. 45° Women Hand Absolute Cream Mask zadovoljava sve potrebe njege ruku u jednom proizvodu. Inovativna formula sadrži organsku kominu masline premium kvalitete iz istarskih eko maslinika, obogaćenu organskim uljem divlje ruže, uljem sjemenki grožđa, uljem lana, ekstraktom gaveza, preslice, nevena, karite maslacem i esencijama vanilije i mažurana, elixir dugovječnosti stanica. Intenzivna i hranjiva poput maske, a brzo upijajuća tekstura koja ne masti omogućuje da se koristi kao krema za svakodnevnu njegu ruku i kao maska u debljem sloju za posebnu njegu ruku."
WOMEN_EN = "Completely natural hand care formulated for women. 45° Women Hand Absolute Cream Mask covers every hand-care need in one product. The innovative formula contains premium organic olive pulp from Istrian eco olive groves, enriched with organic rosehip oil, grape seed oil, linseed oil, extracts of comfrey, horsetail and calendula, shea butter and essences of vanilla and marjoram – an elixir of cell longevity. Intensive and nourishing like a mask, while its fast-absorbing, non-greasy texture lets you use it as an everyday hand cream, or in a thicker layer as a mask for special care."

D = {
  "body-cream-lotion": dict(
    hr=[BASE_LOTION_HR + " Jedinstvena hranjiva formula s uljem avokada, uljem sjemenki grožđa, maslinovim uljem i ekstraktom preslice dubinski njeguje kožu. Nježnog mirisa eteričnih ulja muškatne kadulje, mažurana, mente i vanilije, svilenkaste teksture za svakodnevni ritual njege i ljepote."],
    en=[BASE_LOTION_EN + " A unique nourishing formula with avocado oil, grape seed oil, olive oil and horsetail extract deeply cares for the skin. Gently scented with essential oils of clary sage, marjoram, mint and vanilla, with a silky texture for a daily ritual of care and beauty."],
    use_hr="Nanijeti ujutro i/ili navečer na čistu i suhu kožu. Masirati dlanovima počevši od zapešća prema prsnom košu. Kružnim pokretima masirati u predjelu abdomena prema torzu za poticanje cirkulacije.",
    use_en="Apply in the morning and/or evening to clean, dry skin. Massage with the palms, starting from the wrists towards the chest. Massage the abdomen in circular movements towards the torso to stimulate circulation."),
  "body-polish": dict(hr=[POLISH_HR], en=[POLISH_EN],
    use_hr="Nanijeti do dva puta tjedno na suhu kožu. Masirati kružnim pokretima cijelo tijelo, a posebno u području koljena, laktova i stopala. Neka koža diše.",
    use_en="Apply to dry skin up to twice a week. Massage the whole body in circular movements, especially knees, elbows and feet. Let your skin breathe."),
  "foot-balm": dict(hr=[FOOT_HR], en=[FOOT_EN],
    use_hr="Nanijeti svakodnevno na čistu i suhu kožu stopala. Laganim pritiskom na refleksne zone kružnim pokretima umasirati balzam od prstiju prema sredini stopala. Masažu nastaviti kružnim pokretima u području pete klizeći vanjskom stranom gležnja, pa okružiti oko zgloba u oba smjera.",
    use_en="Apply daily to clean, dry feet. With light pressure on the reflex zones, massage the balm in circular movements from the toes towards the middle of the foot. Continue with circular movements around the heel, sliding along the outer ankle, then circle the joint in both directions."),
  "men-hand-cream": dict(
    hr=["Potpuno prirodna njega ruku od 45 Degrees sadrži organsku kominu masline premium kvalitete iz istarskih eko maslinika, bogati izvor antioksidansa i minerala. Jedinstvena hranjiva formula s uljem avokada, uljem lana, uljem ricinusa, oplemenjena ekstraktom gaveza, preslice, ružmarina i karite maslacem dubinski njeguje kožu. Blagog mirisa lovora i vanilije, bogate teksture za svakodnevnu uporabu."],
    en=["Completely natural hand care by 45 Degrees containing premium organic olive pulp from Istrian eco olive groves, a rich source of antioxidants and minerals. A unique nourishing formula with avocado, linseed and castor oils, enriched with comfrey, horsetail and rosemary extracts and shea butter, deeply cares for the skin. Lightly scented with bay laurel and vanilla, with a rich texture for everyday use."]),
  "women-hand-mask": dict(hr=[WOMEN_HR], en=[WOMEN_EN]),
  "pro-body-cream-lotion": dict(
    hr=[BASE_LOTION_HR + " Pojačana hranjiva formula s uljem avokada, uljem sjemenki grožđa, maslinovim uljem i ekstraktom preslice dubinski njeguje kožu. Intenzivnog mirisa eteričnih ulja muškatne kadulje, mažurana, mente i vanilije, svilenkaste teksture za profesionalnu uporabu."],
    en=[BASE_LOTION_EN + " An enhanced nourishing formula with avocado oil, grape seed oil, olive oil and horsetail extract deeply cares for the skin. Intensely scented with essential oils of clary sage, marjoram, mint and vanilla, with a silky texture for professional use."]),
  "pro-body-polish": dict(hr=[POLISH_HR, "Snažnija formula uz pojačane doze prirodnih sastojaka. Za profesionalnu uporabu."],
                          en=[POLISH_EN, "A stronger formula with higher doses of natural ingredients. For professional use."]),
  "pro-hand-cream-mask": dict(hr=[WOMEN_HR], en=[WOMEN_EN]),
  "pro-foot-balm": dict(hr=[FOOT_HR, "Za profesionalnu uporabu."], en=[FOOT_EN, "For professional use."]),
}
